Now packaging GUI. Very WIP still

diff --git a/deb-package/debhelper/debian/pifmrds/DEBIAN/postinst b/deb-package/debhelper/debian/pifmrds/DEBIAN/postinst
--- a/deb-package/debhelper/debian/pifmrds/DEBIAN/postinst
+++ b/deb-package/debhelper/debian/pifmrds/DEBIAN/postinst
@@ -17,3 +17,20 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
+# Automatically added by dh_installsystemduser/13.2~bpo10+1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper --user unmask 'pifmrds.service' >/dev/null || true
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet --user was-enabled 'pifmrds.service' ; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper --user enable 'pifmrds.service' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper --user update-state 'pifmrds.service' >/dev/null || true
+	fi
+fi
+# End automatically added section
